# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.api.invitations_api import InvitationsApi  # noqa: E501
from clerk_client.rest import ApiException


class TestInvitationsApi(unittest.TestCase):
    """InvitationsApi unit test stubs"""

    def setUp(self):
        self.api = InvitationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_invitation(self):
        """Test case for create_invitation

        Create an invitation  # noqa: E501
        """
        pass

    def test_list_invitations(self):
        """Test case for list_invitations

        List all invitations  # noqa: E501
        """
        pass

    def test_revoke_invitation(self):
        """Test case for revoke_invitation

        Revokes an invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
