# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.api.jwt_templates_api import JWTTemplatesApi  # noqa: E501
from clerk_client.rest import ApiException


class TestJWTTemplatesApi(unittest.TestCase):
    """JWTTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = JWTTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_jwt_template(self):
        """Test case for create_jwt_template

        Create a JWT template  # noqa: E501
        """
        pass

    def test_delete_jwt_template(self):
        """Test case for delete_jwt_template

        Delete a Template  # noqa: E501
        """
        pass

    def test_get_jwt_template(self):
        """Test case for get_jwt_template

        Retrieve a template  # noqa: E501
        """
        pass

    def test_list_jwt_templates(self):
        """Test case for list_jwt_templates

        List all templates  # noqa: E501
        """
        pass

    def test_update_jwt_template(self):
        """Test case for update_jwt_template

        Update a JWT template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
