# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.api.phone_numbers_api import PhoneNumbersApi  # noqa: E501
from clerk_client.rest import ApiException


class TestPhoneNumbersApi(unittest.TestCase):
    """PhoneNumbersApi unit test stubs"""

    def setUp(self):
        self.api = PhoneNumbersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_phone_number(self):
        """Test case for create_phone_number

        Create a phone number  # noqa: E501
        """
        pass

    def test_delete_phone_number(self):
        """Test case for delete_phone_number

        Delete a phone number  # noqa: E501
        """
        pass

    def test_get_phone_number(self):
        """Test case for get_phone_number

        Retrieve a phone number  # noqa: E501
        """
        pass

    def test_update_phone_number(self):
        """Test case for update_phone_number

        Update a phone number  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
