# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.models.o_auth_application_with_secret import OAuthApplicationWithSecret  # noqa: E501
from clerk_client.rest import ApiException


class TestOAuthApplicationWithSecret(unittest.TestCase):
    """OAuthApplicationWithSecret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuthApplicationWithSecret(self):
        """Test OAuthApplicationWithSecret"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.o_auth_application_with_secret.OAuthApplicationWithSecret()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
