# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.models.saml_connections_attribute_mapping import SamlConnectionsAttributeMapping  # noqa: E501
from clerk_client.rest import ApiException


class TestSamlConnectionsAttributeMapping(unittest.TestCase):
    """SamlConnectionsAttributeMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSamlConnectionsAttributeMapping(self):
        """Test SamlConnectionsAttributeMapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.saml_connections_attribute_mapping.SamlConnectionsAttributeMapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
