# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.api.instance_settings_api import InstanceSettingsApi  # noqa: E501
from clerk_client.rest import ApiException


class TestInstanceSettingsApi(unittest.TestCase):
    """InstanceSettingsApi unit test stubs"""

    def setUp(self):
        self.api = InstanceSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_instance(self):
        """Test case for update_instance

        Update instance settings  # noqa: E501
        """
        pass

    def test_update_instance_organization_settings(self):
        """Test case for update_instance_organization_settings

        Update instance organization settings  # noqa: E501
        """
        pass

    def test_update_instance_restrictions(self):
        """Test case for update_instance_restrictions

        Update instance restrictions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
