# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.api.clients_api import ClientsApi  # noqa: E501
from clerk_client.rest import ApiException


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self):
        self.api = ClientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_client(self):
        """Test case for get_client

        Get a client  # noqa: E501
        """
        pass

    def test_get_client_list(self):
        """Test case for get_client_list

        List all clients  # noqa: E501
        """
        pass

    def test_verify_client(self):
        """Test case for verify_client

        Verify a client  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
