# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.api.proxy_checks_api import ProxyChecksApi  # noqa: E501
from clerk_client.rest import ApiException


class TestProxyChecksApi(unittest.TestCase):
    """ProxyChecksApi unit test stubs"""

    def setUp(self):
        self.api = ProxyChecksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_verify_domain_proxy(self):
        """Test case for verify_domain_proxy

        Verify the proxy configuration for your domain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
