# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clerk_client
from clerk_client.models.one_of_phone_number_verification import OneOfPhoneNumberVerification  # noqa: E501
from clerk_client.rest import ApiException


class TestOneOfPhoneNumberVerification(unittest.TestCase):
    """OneOfPhoneNumberVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfPhoneNumberVerification(self):
        """Test OneOfPhoneNumberVerification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_phone_number_verification.OneOfPhoneNumberVerification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
