# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EmailAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'object': 'str',
        'email_address': 'str',
        'reserved': 'bool',
        'verification': 'OneOfEmailAddressVerification',
        'linked_to': 'list[IdentificationLink]'
    }

    attribute_map = {
        'id': 'id',
        'object': 'object',
        'email_address': 'email_address',
        'reserved': 'reserved',
        'verification': 'verification',
        'linked_to': 'linked_to'
    }

    def __init__(self, id=None, object=None, email_address=None, reserved=None, verification=None, linked_to=None):  # noqa: E501
        """EmailAddress - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._object = None
        self._email_address = None
        self._reserved = None
        self._verification = None
        self._linked_to = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.object = object
        self.email_address = email_address
        self.reserved = reserved
        self.verification = verification
        self.linked_to = linked_to

    @property
    def id(self):
        """Gets the id of this EmailAddress.  # noqa: E501


        :return: The id of this EmailAddress.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EmailAddress.


        :param id: The id of this EmailAddress.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def object(self):
        """Gets the object of this EmailAddress.  # noqa: E501

        String representing the object's type. Objects of the same type share the same value.   # noqa: E501

        :return: The object of this EmailAddress.  # noqa: E501
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this EmailAddress.

        String representing the object's type. Objects of the same type share the same value.   # noqa: E501

        :param object: The object of this EmailAddress.  # noqa: E501
        :type: str
        """
        if object is None:
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501
        allowed_values = ["email_address"]  # noqa: E501
        if object not in allowed_values:
            raise ValueError(
                "Invalid value for `object` ({0}), must be one of {1}"  # noqa: E501
                .format(object, allowed_values)
            )

        self._object = object

    @property
    def email_address(self):
        """Gets the email_address of this EmailAddress.  # noqa: E501


        :return: The email_address of this EmailAddress.  # noqa: E501
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address):
        """Sets the email_address of this EmailAddress.


        :param email_address: The email_address of this EmailAddress.  # noqa: E501
        :type: str
        """
        if email_address is None:
            raise ValueError("Invalid value for `email_address`, must not be `None`")  # noqa: E501

        self._email_address = email_address

    @property
    def reserved(self):
        """Gets the reserved of this EmailAddress.  # noqa: E501


        :return: The reserved of this EmailAddress.  # noqa: E501
        :rtype: bool
        """
        return self._reserved

    @reserved.setter
    def reserved(self, reserved):
        """Sets the reserved of this EmailAddress.


        :param reserved: The reserved of this EmailAddress.  # noqa: E501
        :type: bool
        """
        if reserved is None:
            raise ValueError("Invalid value for `reserved`, must not be `None`")  # noqa: E501

        self._reserved = reserved

    @property
    def verification(self):
        """Gets the verification of this EmailAddress.  # noqa: E501


        :return: The verification of this EmailAddress.  # noqa: E501
        :rtype: OneOfEmailAddressVerification
        """
        return self._verification

    @verification.setter
    def verification(self, verification):
        """Sets the verification of this EmailAddress.


        :param verification: The verification of this EmailAddress.  # noqa: E501
        :type: OneOfEmailAddressVerification
        """
        if verification is None:
            raise ValueError("Invalid value for `verification`, must not be `None`")  # noqa: E501

        self._verification = verification

    @property
    def linked_to(self):
        """Gets the linked_to of this EmailAddress.  # noqa: E501


        :return: The linked_to of this EmailAddress.  # noqa: E501
        :rtype: list[IdentificationLink]
        """
        return self._linked_to

    @linked_to.setter
    def linked_to(self, linked_to):
        """Sets the linked_to of this EmailAddress.


        :param linked_to: The linked_to of this EmailAddress.  # noqa: E501
        :type: list[IdentificationLink]
        """
        if linked_to is None:
            raise ValueError("Invalid value for `linked_to`, must not be `None`")  # noqa: E501

        self._linked_to = linked_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmailAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
