# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from clerk_client.models.invitation import Invitation  # noqa: F401,E501

class InlineResponse2005(Invitation):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'revoked': 'bool',
        'status': 'str'
    }
    if hasattr(Invitation, "swagger_types"):
        swagger_types.update(Invitation.swagger_types)

    attribute_map = {
        'revoked': 'revoked',
        'status': 'status'
    }
    if hasattr(Invitation, "attribute_map"):
        attribute_map.update(Invitation.attribute_map)

    def __init__(self, revoked=None, status=None, *args, **kwargs):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger"""  # noqa: E501
        self._revoked = None
        self._status = None
        self.discriminator = None
        if revoked is not None:
            self.revoked = revoked
        if status is not None:
            self.status = status
        Invitation.__init__(self, *args, **kwargs)

    @property
    def revoked(self):
        """Gets the revoked of this InlineResponse2005.  # noqa: E501


        :return: The revoked of this InlineResponse2005.  # noqa: E501
        :rtype: bool
        """
        return self._revoked

    @revoked.setter
    def revoked(self, revoked):
        """Sets the revoked of this InlineResponse2005.


        :param revoked: The revoked of this InlineResponse2005.  # noqa: E501
        :type: bool
        """

        self._revoked = revoked

    @property
    def status(self):
        """Gets the status of this InlineResponse2005.  # noqa: E501


        :return: The status of this InlineResponse2005.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2005.


        :param status: The status of this InlineResponse2005.  # noqa: E501
        :type: str
        """
        allowed_values = ["revoked"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2005, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2005):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
