# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InvitationIdRevokeBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'requesting_user_id': 'str'
    }

    attribute_map = {
        'requesting_user_id': 'requesting_user_id'
    }

    def __init__(self, requesting_user_id=None):  # noqa: E501
        """InvitationIdRevokeBody - a model defined in Swagger"""  # noqa: E501
        self._requesting_user_id = None
        self.discriminator = None
        self.requesting_user_id = requesting_user_id

    @property
    def requesting_user_id(self):
        """Gets the requesting_user_id of this InvitationIdRevokeBody.  # noqa: E501

        The ID of the user that revokes the invitation. Must be an administrator in the organization.  # noqa: E501

        :return: The requesting_user_id of this InvitationIdRevokeBody.  # noqa: E501
        :rtype: str
        """
        return self._requesting_user_id

    @requesting_user_id.setter
    def requesting_user_id(self, requesting_user_id):
        """Sets the requesting_user_id of this InvitationIdRevokeBody.

        The ID of the user that revokes the invitation. Must be an administrator in the organization.  # noqa: E501

        :param requesting_user_id: The requesting_user_id of this InvitationIdRevokeBody.  # noqa: E501
        :type: str
        """
        if requesting_user_id is None:
            raise ValueError("Invalid value for `requesting_user_id`, must not be `None`")  # noqa: E501

        self._requesting_user_id = requesting_user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvitationIdRevokeBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvitationIdRevokeBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
