# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@clerk.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OauthApplicationsOauthApplicationIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'callback_url': 'str',
        'scopes': 'str'
    }

    attribute_map = {
        'name': 'name',
        'callback_url': 'callback_url',
        'scopes': 'scopes'
    }

    def __init__(self, name=None, callback_url=None, scopes='profile email'):  # noqa: E501
        """OauthApplicationsOauthApplicationIdBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._callback_url = None
        self._scopes = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if callback_url is not None:
            self.callback_url = callback_url
        if scopes is not None:
            self.scopes = scopes

    @property
    def name(self):
        """Gets the name of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501

        The new name of the OAuth application  # noqa: E501

        :return: The name of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OauthApplicationsOauthApplicationIdBody.

        The new name of the OAuth application  # noqa: E501

        :param name: The name of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def callback_url(self):
        """Gets the callback_url of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501

        The new callback URL of the OAuth application  # noqa: E501

        :return: The callback_url of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501
        :rtype: str
        """
        return self._callback_url

    @callback_url.setter
    def callback_url(self, callback_url):
        """Sets the callback_url of this OauthApplicationsOauthApplicationIdBody.

        The new callback URL of the OAuth application  # noqa: E501

        :param callback_url: The callback_url of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501
        :type: str
        """

        self._callback_url = callback_url

    @property
    def scopes(self):
        """Gets the scopes of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501

        Define the allowed scopes for the new OAuth applications that dictate the user payload of the OAuth user info endpoint. Available scopes are `profile`, `email`, `public_metadata`, `private_metadata`. Provide the requested scopes as a string, separated by spaces.  # noqa: E501

        :return: The scopes of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501
        :rtype: str
        """
        return self._scopes

    @scopes.setter
    def scopes(self, scopes):
        """Sets the scopes of this OauthApplicationsOauthApplicationIdBody.

        Define the allowed scopes for the new OAuth applications that dictate the user payload of the OAuth user info endpoint. Available scopes are `profile`, `email`, `public_metadata`, `private_metadata`. Provide the requested scopes as a string, separated by spaces.  # noqa: E501

        :param scopes: The scopes of this OauthApplicationsOauthApplicationIdBody.  # noqa: E501
        :type: str
        """

        self._scopes = scopes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OauthApplicationsOauthApplicationIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OauthApplicationsOauthApplicationIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
